# Cluster: platform
apiVersion: core.open-control-plane.io/v1alpha1
kind: Replica
metadata:
  name: simple
  namespace: test-01
  finalizers:
  - replica.core.open-control-plane.io/finalizer
spec:
  sources:
  - id: source
    group: ""
    version: v1
    kind: Secret
    name: cryptic
    namespace: foo
  targets:
  - cluster:
      selector:
        matchPurposes:
        - operator: ContainsAll
          values:
          - workload
    namespace:
      selector:
        matchExpressions:
        - key: foo.bar.baz/target
          operator: Exists
status:
  phase: Ready
  observedGeneration: 0
  conditions:
  - message: "Successfully accessed cluster 'workloads/wl-01'"
    reason: TargetClusterAccess
    status: "True"
    type: Cluster_workloads.wl-01
  - message: "Successfully accessed cluster 'workloads/wl-02'"
    reason: TargetClusterAccess
    status: "True"
    type: Cluster_workloads.wl-02
  - message: ""
    reason: Meta_True
    status: "True"
    type: Meta
  - message: "Source resource 'foo/cryptic' (id: source) successfully read"
    reason: SourceRead
    status: "True"
    type: Source_foo.cryptic_Secret.v1
  - message: "Target resource 'abc/cryptic' (/v1, Kind=Secret) successfully synced to cluster 'workloads/wl-01'"
    reason: TargetSynced
    status: "True"
    type: Target_workloads.wl-01_abc.cryptic_Secret.v1
  - message: "Target resource 'xyz/cryptic' (/v1, Kind=Secret) successfully synced to cluster 'workloads/wl-01'"
    reason: TargetSynced
    status: "True"
    type: Target_workloads.wl-01_xyz.cryptic_Secret.v1
  - message: "Target resource 'test/cryptic' (/v1, Kind=Secret) successfully synced to cluster 'workloads/wl-02'"
    reason: TargetSynced
    status: "True"
    type: Target_workloads.wl-02_test.cryptic_Secret.v1
  replicas:
  - type:
      group: ""
      version: v1
      kind: Secret
    resources:
    - cluster:
        name: wl-01
        namespace: workloads
      name: cryptic
      namespace: abc
    - cluster:
        name: wl-01
        namespace: workloads
      name: cryptic
      namespace: xyz
    - cluster:
        name: wl-02
        namespace: workloads
      name: cryptic
      namespace: test
      