# Clusters:
# - workloads/wl-01
apiVersion: v1
kind: Secret
metadata:
  name: cryptic
  namespace: abc
  labels:
    app: foo
  annotations:
    foo.bar.baz/ann: "true"
type: Opaque
data:
  password: cGFzc3dvcmQxMjM=