# Cluster: platform
apiVersion: core.open-control-plane.io/v1alpha1
kind: Replica
metadata:
  name: imagepull-next-to
  namespace: test-01
  finalizers:
  - replica.core.open-control-plane.io/finalizer
spec:
  sources:
  - id: source
    group: ""
    version: v1
    kind: Secret
    name: imagepull
    namespace: registry
  template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: "imagepull-{{ .target.cluster.name }}"
    type: "{{ .sources.source.type }}"
    data:
      .dockerconfigjson: "{{ index .sources.source.data \".dockerconfigjson\" }}"
  targets:
  - cluster:
      selector:
        matchPurposes:
        - operator: ContainsAll
          values:
          - controlplane
      location: NextTo
status:
  phase: Ready
  observedGeneration: 0
  conditions:
  - message: "Successfully accessed cluster 'user-01/cp-01'"
    reason: TargetClusterAccess
    status: "True"
    type: Cluster_user-01.cp-01
  - message: "Successfully accessed cluster 'user-02/cp-01'"
    reason: TargetClusterAccess
    status: "True"
    type: Cluster_user-02.cp-01
  - message: "Successfully accessed cluster 'user-02/cp-02'"
    reason: TargetClusterAccess
    status: "True"
    type: Cluster_user-02.cp-02
  - message: ""
    reason: Meta_True
    status: "True"
    type: Meta
  - message: "Source resource 'registry/imagepull' (id: source) successfully read"
    reason: SourceRead
    status: "True"
    type: Source_registry.imagepull_Secret.v1
  - message: "Target resource 'user-01/imagepull-cp-01' (/v1, Kind=Secret) successfully synced to cluster 'user-01/cp-01'"
    reason: TargetSynced
    status: "True"
    type: Target_user-01.cp-01_user-01.imagepull-cp-01_Secret.v1
  - message: "Target resource 'user-02/imagepull-cp-01' (/v1, Kind=Secret) successfully synced to cluster 'user-02/cp-01'"
    reason: TargetSynced
    status: "True"
    type: Target_user-02.cp-01_user-02.imagepull-cp-01_Secret.v1
  - message: "Target resource 'user-02/imagepull-cp-02' (/v1, Kind=Secret) successfully synced to cluster 'user-02/cp-02'"
    reason: TargetSynced
    status: "True"
    type: Target_user-02.cp-02_user-02.imagepull-cp-02_Secret.v1
  replicas:
  - type:
      group: ""
      version: v1
      kind: Secret
    resources:
    - name: imagepull-cp-01
      namespace: user-01
    - name: imagepull-cp-01
      namespace: user-02
    - name: imagepull-cp-02
      namespace: user-02
