# Cluster: platform
# Namespace: user-02 (same namespace as Cluster resource 'user-02/cp-02')
apiVersion: v1
kind: Secret
metadata:
  name: imagepull-cp-02
  namespace: user-02
  labels:
    openmcp.cloud/managed-by: replica
    replica.core.open-control-plane.io/generation: "0"
    replica.core.open-control-plane.io/kind: replica
    replica.core.open-control-plane.io/name: imagepull-next-to
    replica.core.open-control-plane.io/namespace: test-01
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJzb21lYXV0aHRva2VuIn19fQ==
