# Cluster: platform
# Namespace: user-02 (same namespace as Cluster resource 'user-02/cp-01')
apiVersion: v1
kind: Secret
metadata:
  name: imagepull-cp-01
  namespace: user-02
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJzb21lYXV0aHRva2VuIn19fQ==
