# Cluster: platform
apiVersion: core.open-control-plane.io/v1alpha1
kind: Replica
metadata:
  name: combined-secret
  namespace: test-01
  finalizers:
  - replica.core.open-control-plane.io/finalizer
spec:
  sources:
  - id: db
    group: ""
    version: v1
    kind: Secret
    name: db-credentials
    namespace: infra
  - id: tls
    group: ""
    version: v1
    kind: Secret
    name: tls-cert
    namespace: infra
  template: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: combined
      namespace: test-01
    type: Opaque
    data:
      password: {{ index .sources.db.data "password" }}
      {{- range $key, $value := .sources.tls.data }}
      {{ $key }}: {{ $value }}
      {{- end }}
  targets:
  - namespace:
      selector:
        matchIdentities:
        - name: test-01
status:
  phase: Ready
  observedGeneration: 0
  conditions:
  - message: "Successfully accessed cluster '<hosting-platform-cluster>'"
    reason: TargetClusterAccess
    status: "True"
    type: Cluster_HostingPlatformCluster
  - message: ""
    reason: Meta_True
    status: "True"
    type: Meta
  - message: "Source resource 'infra/db-credentials' (id: db) successfully read"
    reason: SourceRead
    status: "True"
    type: Source_infra.db-credentials_Secret.v1
  - message: "Source resource 'infra/tls-cert' (id: tls) successfully read"
    reason: SourceRead
    status: "True"
    type: Source_infra.tls-cert_Secret.v1
  - message: "Target resource 'test-01/combined' (/v1, Kind=Secret) successfully synced to cluster '<hosting-platform-cluster>'"
    reason: TargetSynced
    status: "True"
    type: Target_HostingPlatformCluster_test-01.combined_Secret.v1
  replicas:
  - type:
      group: ""
      version: v1
      kind: Secret
    resources:
    - name: combined
      namespace: test-01
