# Cluster: platform
apiVersion: core.open-control-plane.io/v1alpha1
kind: ClusterReplica
metadata:
  name: simple
  finalizers:
  - replica.core.open-control-plane.io/finalizer
spec:
  sources:
  - id: source
    group: ""
    version: v1
    kind: Secret
    name: cryptic
    namespace: foo
  targets:
  - namespace:
      selector:
        matchIdentities:
        - name: bar
status:
  phase: Ready
  observedGeneration: 0
  conditions:
  - message: "Successfully accessed cluster '<hosting-platform-cluster>'"
    reason: TargetClusterAccess
    status: "True"
    type: Cluster_HostingPlatformCluster
  - message: ""
    reason: Meta_True
    status: "True"
    type: Meta
  - message: "Source resource 'foo/cryptic' (id: source) successfully read"
    reason: SourceRead
    status: "True"
    type: Source_foo.cryptic_Secret.v1
  - message: "Target resource 'bar/cryptic' (/v1, Kind=Secret) successfully synced to cluster '<hosting-platform-cluster>'"
    reason: TargetSynced
    status: "True"
    type: Target_HostingPlatformCluster_bar.cryptic_Secret.v1
  replicas:
  - type:
      group: ""
      version: v1
      kind: Secret
    resources:
    - name: cryptic
      namespace: bar